In [1]:
import os
import torch.nn as nn
import torch.nn.functional as F
import math
import torch
import positional_encodings
from datasets.cityscapes import cityscapesDataset
from datasets.pascalvoc import pascalVOCDataset
import matplotlib.pyplot as plt
from networks.hanet import HANet

In [2]:
local_path = "./VOCdevkit/VOC2012"
pckgs_names = ["gtFine_trainvaltest.zip","leftImg8bit_trainvaltest.zip"]
dir_names = ["gtFine", "leftImg8bit"]

In [3]:
training_data = pascalVOCDataset(local_path, split="train")
len(training_data)

1464

In [5]:
img, lbl = training_data[0]

In [6]:
img.size()

torch.Size([3, 512, 512])

In [9]:
model = HANet((64, 512, 512), (128, 512, 512))
model

HANet(
  (ww_pooling): AvgPool2d(kernel_size=(1, 512), stride=(1, 1), padding=0)
  (down): Upsample(size=(16, 1), mode=bilinear)
  (convs): Sequential(
    (0): Conv1dPosEncRelu(
      (conv): Conv1d(64, 2, kernel_size=(1,), stride=(1,))
      (relu): ReLU()
    )
    (1): Conv1dPosEncRelu(
      (conv): Conv1d(2, 4, kernel_size=(1,), stride=(1,))
      (relu): ReLU()
    )
    (2): Conv1dPosEncSigmoid(
      (conv): Conv1d(4, 128, kernel_size=(1,), stride=(1,))
      (sigmoid): Sigmoid()
    )
  )
  (up): Upsample(size=(512, 1), mode=bilinear)
)

In [10]:
model.eval()
outputs = model.forward(torch.rand(1,64,512,512))

X_l =  torch.Size([64, 512, 512])
Z =  torch.Size([64, 512, 1])
Z_hat =  torch.Size([64, 16])
 Q_1 =  torch.Size([2, 16])
 Q_2 =  torch.Size([4, 16])
 Q_3 =  torch.Size([128, 16])
A_hat =  torch.Size([128, 16, 1])
A =  torch.Size([128, 512, 1])


In [119]:
my_tensor = torch.Tensor([[
    [6,5, 12],
    [1,2, -2],
    [3,4, 5]], 
    [
    [1,2,4],
    [4,5,2], 
    [9,44,43]]])
my_tensor.size()

torch.Size([2, 3, 3])

In [120]:
my_tensor

tensor([[[ 6.,  5., 12.],
         [ 1.,  2., -2.],
         [ 3.,  4.,  5.]],

        [[ 1.,  2.,  4.],
         [ 4.,  5.,  2.],
         [ 9., 44., 43.]]])

In [121]:
my_tensor

tensor([[[ 6.,  5., 12.],
         [ 1.,  2., -2.],
         [ 3.,  4.,  5.]],

        [[ 1.,  2.,  4.],
         [ 4.,  5.,  2.],
         [ 9., 44., 43.]]])

In [122]:
my_tensor.size()

torch.Size([2, 3, 3])

In [123]:
model = HANet(in_dims=(2,2,3), out_dims=(3,3,1))

In [124]:
my_tensor = model.forward(my_tensor.unsqueeze(0))
my_tensor

/home/pabvald/Documents/DSAI/simple-imageseg/.env/lib/python3.7/site-packages/torch/nn/functional.py:3455: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)


tensor([[[[ 5.8333],
          [ 3.0833]],

         [[ 2.6667],
          [24.9167]]]])

In [17]:
my_tensor = torch.rand(1,3,2,1)

In [18]:
my_tensor.size()

torch.Size([1, 3, 2, 1])

In [19]:
my_tensor

tensor([[[[0.5975],
          [0.6271]],

         [[0.1415],
          [0.5546]],

         [[0.8905],
          [0.5586]]]])

In [20]:
my_tensor = F.interpolate(my_tensor, size=(4,2), mode="bilinear")

In [21]:
my_tensor.size()

torch.Size([1, 3, 4, 2])

In [22]:
my_tensor

tensor([[[[0.5975, 0.5975],
          [0.6049, 0.6049],
          [0.6197, 0.6197],
          [0.6271, 0.6271]],

         [[0.1415, 0.1415],
          [0.2448, 0.2448],
          [0.4514, 0.4514],
          [0.5546, 0.5546]],

         [[0.8905, 0.8905],
          [0.8075, 0.8075],
          [0.6415, 0.6415],
          [0.5586, 0.5586]]]])